apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: e-charging
  labels:
    app: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    app: frontend