apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reservation-disk
  namespace: e-charging
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi